CREATE TABLE IF NOT EXISTS "character_ability" (
	"id" integer PRIMARY KEY NOT NULL,
	"pattern_id" integer,
	"node_id" integer,
	"level" integer,
	"type" text,
	"parameter" integer,
	"target_quest_types" text,
	"exclude_quest_types" text,
	"type2" text,
	"parameter2" integer,
	"target_quest_types2" text,
	"exclude_quest_types2" text,
	"unlock_character_level" integer,
	"unlock_second_phase" integer,
	"consume_m_character1_id" integer,
	"consume_m_character1_amount" integer,
	"consume_m_character2_id" integer,
	"consume_m_character2_amount" integer,
	"consume_m_character3_id" integer,
	"consume_m_character3_amount" integer,
	"consume_piece_type" text,
	"consume_piece_rank" integer,
	"small_piece" integer,
	"middle_piece" integer,
	"large_piece" integer,
	"consume_coin" integer,
	"consume_gold_const" integer,
	"is_link_skill" integer
);
