CREATE TABLE IF NOT EXISTS "t3turbo_character" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"full_name" text NOT NULL,
	"name_phonetic" text NOT NULL,
	"variation" text NOT NULL,
	"chara_identity_id" text NOT NULL,
	"resource_2d_id" text NOT NULL,
	"resource_3d_id" text NOT NULL,
	"disable_chara_image_drop_shadow" integer NOT NULL,
	"rarity" integer NOT NULL,
	"character_category" text NOT NULL,
	"character_element" integer NOT NULL,
	"is_resurrect" integer NOT NULL,
	"init_hp" integer NOT NULL,
	"init_sp" integer NOT NULL,
	"init_atk" integer NOT NULL,
	"init_def" integer NOT NULL,
	"init_crt" integer NOT NULL,
	"first_max_hp" integer NOT NULL,
	"first_max_sp" integer NOT NULL,
	"first_max_atk" integer NOT NULL,
	"first_max_def" integer NOT NULL,
	"first_max_crt" integer NOT NULL,
	"second_max_hp" integer NOT NULL,
	"second_max_sp" integer NOT NULL,
	"second_max_atk" integer NOT NULL,
	"second_max_def" integer NOT NULL,
	"second_max_crt" integer NOT NULL,
	"third_max_hp" integer NOT NULL,
	"third_max_sp" integer NOT NULL,
	"third_max_atk" integer NOT NULL,
	"third_max_def" integer NOT NULL,
	"third_max_crt" integer NOT NULL,
	"dash_type" text NOT NULL,
	"speed" integer NOT NULL,
	"character_attack_group_id_normal" integer NOT NULL,
	"character_attack_group_id_heavy1" integer NOT NULL,
	"character_attack_group_id_heavy2" integer NOT NULL,
	"character_attack_group_id_heavy3" integer NOT NULL,
	"character_attack_group_id_ex" integer NOT NULL,
	"ex_atk_resource_3d_id" text NOT NULL,
	"ex_cutin_resource_3d_id" text NOT NULL,
	"character_shift_id" integer NOT NULL,
	"character_buddy_id" integer NOT NULL,
	"killer_type1" text,
	"killer_type2" text,
	"max_ex_gauge" integer NOT NULL,
	"m_soul_piece_pattern_id" integer NOT NULL,
	"m_potential_material_pattern_id" integer NOT NULL,
	"m_passive_ability_group_id" integer NOT NULL,
	"m_arena_skill_group_id" integer NOT NULL,
	"m_arena_ability_group_id" integer NOT NULL,
	"profile" text NOT NULL,
	"short_profile" text NOT NULL,
	"ex_introduction_name" text NOT NULL,
	"ex_introduction_description" text NOT NULL,
	"book_order" integer NOT NULL,
	"start_date" timestamp,
	"stand_animation_state" text,
	"quest_start_voice_event" text,
	"stand_face" integer NOT NULL,
	"image_scale" integer NOT NULL,
	"gacha_message_bank_event" text,
	"gacha_message_direction" text,
	"gacha_message_dict_key" text,
	"gacha_particle_pattern" text,
	"background_image_path" text,
	"disable_unlock_item" integer,
	"potential_point" integer,
	"boost_gauge_trigger" text,
	"m_boost_gauge_ability_group_id" integer
);
