name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: npm run format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Typecheck
        run: npm run typecheck
